name: bounded

num_target_views: 2
num_context_views: 8

min_distance_between_context_views: 2
max_distance_between_context_views: 40
min_distance_to_context_views: 0

warm_up_steps: 10_000
initial_min_distance_between_context_views: 2
initial_max_distance_between_context_views: 12
